[project]
name = "pyraytracing"
version = "0.1.0"
description = "Python implementation of the 'Ray Tracing in One Weekend'."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "test",
]
